CREATE TABLE POWERBANKEN.PRODUCT(

SKU				NVARCHAR(MAX)	NOT NULL,
PRODUCTNAME		NVARCHAR(MAX)	NOT NULL,
PURCHASEPRICE	FLOAT			NOT NULL,
AMOUNT			INT				NOT NULL,
MINSTOCK		INT				NOT NULL,
PRODUCTTYPE		INT				NOT NULL,
BRANDID			INT				NOT NULL,
LEADTIMEDAYS	INT				DEFAULT 0,
ISACTIVE		BIT				DEFAULT 1,
CONSTRAINT		FK_BRAND		FOREIGN KEY(BRANDID)
				REFERENCES POWERBANKEN.BRAND(BRANDID)
				ON UPDATE CASCADE
				ON DELETE CASCADE,
CONSTRAINT		FK_PRODUCTTYPE	FOREIGN KEY(PRODUCTTYPE)
				REFERENCES POWERBANKEN.PRODUCTTYPE(TYPEID)
				ON UPDATE CASCADE
				ON DELETE CASCADE
)