CREATE TABLE POWERBANKEN.BRAND(
BRANDID			INT				IDENTITY(1,1) PRIMARY KEY,
BRANDNAME		NVARCHAR(50)	NOT NULL,
)

CREATE TABLE POWERBANKEN.PRODUCTTYPE(
TYPEID			INT				IDENTITY(1,1) PRIMARY KEY,
PRODUCTTYPE		NVARCHAR(50)	NOT NULL,
)

CREATE TABLE POWERBANKEN.PRODUCT(

PRODUCTID		INT				IDENTITY(1,1) PRIMARY KEY,
PRODUCTNAME		NVARCHAR(MAX)	NOT NULL,
SKU				NVARCHAR(MAX)	NOT NULL,
PURCHASEPRICE	FLOAT			NOT NULL,
AMOUNT			INT				NOT NULL,
MINSTOCK		INT				NOT NULL,
MAXSTOCK		INT				NOT NULL,
PRODUCTIONINHOURS  FLOAT		NOT NULL,
PRODUCTTYPE		INT				NOT NULL,
BRANDID			INT				NOT NULL,
CONSTRAINT		FK_BRAND		FOREIGN KEY(BRANDID)
				REFERENCES POWERBANKEN.BRAND(BRANDID)
				ON UPDATE CASCADE
				ON DELETE CASCADE,
CONSTRAINT		FK_PRODUCTTYPE	FOREIGN KEY(PRODUCTTYPE)
				REFERENCES POWERBANKEN.PRODUCTTYPE(TYPEID)
				ON UPDATE CASCADE
				ON DELETE CASCADE
)

